### ISSUE TITLE
First test

### ISSUE THREAD

**Issue by gp-slick-coder** [bent10/boox#84]
![image](https://github.com/user-attachments/assets/b55efc44-8b32-4b6e-8fae-133bdc1cbe86)

Is there a way to improve the search result for, e.g. "tes"?

**Comment by bent10** [comment]
@gp-slick-coder The query `"tes"` is short and might be a substring of many documents, leading to less-relevant results.

One approach to improve results is to filter based on the `score` property of each `SearchResult` object. This property indicates the relevance of the document to the search query. Try this:

```js
const results = await boox.search('tes')
const filteredResults = results.filter(result => result.score > 0.1) // Adjust 0.1 as needed
// ... updateUI(filteredResults) ...
```

Experiment with different score **thresholds** (e.g., 0.05, 0.2, 0.4) to find what works best for your dataset. A higher threshold will return fewer, but potentially more relevant, results.

Please refer to the [Filtering Search Result guide](https://stilearning.com/boox/guides/search-results.html#filtering) for more details.

**Comment by gp-slick-coder** [comment]
Thanks, I'll try that.
